### PR TITLE
get_mark_image(): Fallback to default font if Arial font is not found

### PR DESCRIPTION
**Pull request by bachhh**
Hi, thanks for the very optimized tool. There's this problem I have on Linux where font `Ariel.ttf` ( Microsoft's font ) is not found on Linux system.

I believe, at least for Raw and CBZ format, the fonts should not matter when we are downloading raw png image. So I propose we add an optional flag to enable ignore `FontNotFound` exception, it is `False` by default

### CODE REVIEW

**Comment by mansuf** [comment]
> I believe, at least for Raw and CBZ format, the fonts should not matter when we are downloading raw png image.

It actually matter if you download in any `volume` or `single` format. Because `get_mark_image()` is for writing chapter info 
 in start of the chapter. 

If i recall correctly, you want to add optional feature to ignore creating chapter info in start of the chapter.

**Comment by bachhh** [comment]
Oh sorry, I was misunderstanding the purpose of `get_mark_image()`. What I'm trying to fix is the lack of Arial font on my Linux is preventing me from using `--save-as cbz-volume`. 
I suppose adding some fallback fonts for Linux system like `calibri` can solve this.

**Comment by mansuf** [comment]
I have added some improvements and some fonts for linux (`FreeSans.ttf` from GNU FreeFont)

**Comment by bachhh** [comment]
Oh ok thanks, 
I was looking up ImageFont and there's a `ImageFont.load_default()` option which return a hardcoded bitmap font  object. This should always guarantee we have at least some font loaded.

https://pillow.readthedocs.io/en/stable/_modules/PIL/ImageFont.html#load_default

**Comment by bachhh** [comment]
Oh ok thanks, I suppose there's no ideal solution here, other than having to ship a default font in this repo itself.

**Comment by mansuf** [comment]
Yeah, there was some consequences when using default font. It's up to users to install recommended fonts or use the default one.

Anyway, thank you for your contribution 💖. I will merge this to main branch

**Pull request merged**
